export const config = {
  port:                  process.env.PORT || 8000,
  nodeEnv:               process.env.NODE_ENV || 'development',
  frontendUrl:           process.env.FRONTEND_URL || 'http://localhost:5173',
  mongoUrl:              process.env.MONGO_URL,
  dbName:                process.env.DB_NAME || 'welldhan_db',
  jwtSecret:             process.env.JWT_SECRET,
  jwtExpiresIn:          '30d',
  adminJwtExpiresIn:     '8h',
  emailFrom:             process.env.EMAIL_FROM,
  gmailUser:             process.env.GMAIL_USER,
  gmailAppPassword:      process.env.GMAIL_APP_PASSWORD,
  twofactorApiKey:       process.env.TWOFACTOR_API_KEY,
  twofactorOtpTemplate:  process.env.TWOFACTOR_OTP_TEMPLATE,
  twofactorOtpSender:    process.env.TWOFACTOR_OTP_SENDER,
  stripeSecretKey:       process.env.STRIPE_SECRET_KEY,
  upiId:                 process.env.UPI_ID || 'welldhan@okicici',
  managerPhone:          process.env.MANAGER_PHONE,
  adminEmail:            process.env.ADMIN_EMAIL,
  adminPassword:         process.env.ADMIN_PASSWORD,
}